/**
 * Processes the selected photographs into public/img/ and writes the
 * attribution data that /credits publishes.
 *
 * Outputs AVIF + WebP at two widths per slot, plus a tiny blurred placeholder
 * inlined as a data URI so cards do not flash empty while the image loads.
 *
 * ⚠️ Attribution is a LEGAL OBLIGATION for the CC BY and CC BY-SA images here,
 * not a courtesy. Every slot must end up in src/data/photos.ts.
 */
import sharp from "sharp";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { SLOTS } from "./slots.mjs";

const RAW = "scripts/photos/raw";
const CAND = "scripts/photos/cand";
const OUT = "public/img";

const RATIOS = { wide: 16 / 9, square: 1 };
const WIDTHS = { wide: [1600, 800], square: [900, 450] };

const selection = JSON.parse(await readFile("scripts/photos/selection.json", "utf8"));
const rawManifest = JSON.parse(await readFile(`${RAW}/manifest.json`, "utf8"));

await mkdir(OUT, { recursive: true });
const records = [];

for (const slot of SLOTS) {
  const sel = selection[slot.id];
  if (!sel) { console.log(`  SKIP ${slot.id} (not selected)`); continue; }

  let src, meta;

  if (sel.from === "raw") {
    src = `${RAW}/${slot.id}.jpg`;
    const m = rawManifest.find((r) => r.slot === slot.id);
    meta = { title: m.title, license: m.license, licenseUrl: m.licenseUrl, author: m.author, source: m.source };
  } else {
    src = `${CAND}/${slot.id}/${sel.pick}.jpg`;
    const list = JSON.parse(await readFile(`${CAND}/${slot.id}/candidates.json`, "utf8"));
    const c = list.find((x) => x.file === `${sel.pick}.jpg`);
    meta = { title: c.title, license: c.license, licenseUrl: c.licenseUrl, author: c.author, source: c.descUrl };
  }

  const ratio = RATIOS[slot.ratio];
  const widths = WIDTHS[slot.ratio];
  /* sharp's "attention" crop chases saliency and occasionally lands on a
     blurred foreground; `position` overrides it per slot. */
  const position = sel.position === "centre" ? "centre" : "attention";

  for (const w of widths) {
    const h = Math.round(w / ratio);
    const base = sharp(src).resize(w, h, { fit: "cover", position });
    await base.clone().avif({ quality: 55, effort: 5 }).toFile(`${OUT}/${slot.id}-${w}.avif`);
    await base.clone().webp({ quality: 72 }).toFile(`${OUT}/${slot.id}-${w}.webp`);
  }

  /* 20px blurred LQIP, inlined — no extra request. */
  const lqipW = 20;
  const lqip = await sharp(src)
    .resize(lqipW, Math.round(lqipW / ratio), { fit: "cover", position })
    .blur(1.2).webp({ quality: 40 }).toBuffer();

  const sizes = await Promise.all(
    widths.flatMap((w) => ["avif", "webp"].map(async (ext) => {
      const { size } = await sharp(`${OUT}/${slot.id}-${w}.${ext}`).metadata()
        .then(async () => ({ size: (await readFile(`${OUT}/${slot.id}-${w}.${ext}`)).length }));
      return { w, ext, size };
    })),
  );

  records.push({
    id: slot.id,
    alt: slot.alt,
    ratio: slot.ratio,
    widths,
    lqip: `data:image/webp;base64,${lqip.toString("base64")}`,
    ...meta,
  });

  const kb = sizes.map((s) => `${s.ext}${s.w}:${Math.round(s.size / 1024)}k`).join(" ");
  console.log(`  ${slot.id.padEnd(22)} ${kb}`);
}

/* --- Emit the typed data module ---------------------------------------- */
const ts = `/**
 * Photography manifest — GENERATED by scripts/photos/build.mjs. Do not edit.
 *
 * Every image is sourced from Wikimedia Commons under a licence permitting
 * commercial use and modification. Several are CC BY or CC BY-SA, which make
 * attribution a LEGAL REQUIREMENT — it is published at /credits. Removing that
 * page, or an entry from it, breaches the licence.
 *
 * These are illustrative stock photographs, NOT pictures of Mishk Overseas'
 * own premises, goods, staff or vessels. They must never be captioned or
 * presented as though they were. See ASSETS.md §5.
 */

export type Photo = {
  id: string;
  /** Describes the image itself — never implies it depicts Mishk's own assets. */
  alt: string;
  ratio: "wide" | "square";
  widths: number[];
  /** Inlined 20px blurred placeholder. */
  lqip: string;
  title: string;
  license: string;
  licenseUrl: string;
  author: string;
  source: string;
};

export const photos: Photo[] = ${JSON.stringify(records, null, 2)};

export const getPhoto = (id: string) => photos.find((p) => p.id === id);
`;

await writeFile("src/data/photos.ts", ts);
console.log(`\n  ${records.length} photos -> public/img/ + src/data/photos.ts`);
