/**
 * Photography manifest — GENERATED by scripts/photos/build.mjs. Do not edit.
 *
 * Every image is sourced from Wikimedia Commons under a licence permitting
 * commercial use and modification. Several are CC BY or CC BY-SA, which make
 * attribution a LEGAL REQUIREMENT — it is published at /credits. Removing that
 * page, or an entry from it, breaches the licence.
 *
 * These are illustrative stock photographs, NOT pictures of Mishk Overseas'
 * own premises, goods, staff or vessels. They must never be captioned or
 * presented as though they were. See ASSETS.md §5.
 */

export type Photo = {
  id: string;
  /** Describes the image itself — never implies it depicts Mishk's own assets. */
  alt: string;
  ratio: "wide" | "square";
  widths: number[];
  /** Inlined 20px blurred placeholder. */
  lqip: string;
  title: string;
  license: string;
  licenseUrl: string;
  author: string;
  source: string;
};

export const photos: Photo[] = [
  {
    "id": "hero",
    "alt": "A container ship berthed at a terminal beneath gantry cranes",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUAAsAPu1kqk4ppaQiMAgBMB2JYgCdABGvUG761/PAAPcGzicj2MbYGDHnKXzwohETf8fWuGHYTToK5/W04AAA",
    "title": "Container Ship at Conley Terminal.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "author": "Eric Kilby",
    "source": "https://commons.wikimedia.org/wiki/File:Container_Ship_at_Conley_Terminal.jpg"
  },
  {
    "id": "discipline-supplies",
    "alt": "Cartons stacked on high warehouse racking",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoUAAsAPu1mq04ppaQiMAgBMB2JZwAARoEN5/ybTUAAAP1z8ZoGD2m16XzSmgv+HDuA/HnCnbTxbi4mfn1dh+fB9LAAAA==",
    "title": "Warehouse filled with stacked pallets showcasing efficient space usage during daytime operations.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "author": "Shixart1985",
    "source": "https://commons.wikimedia.org/wiki/File:Warehouse_filled_with_stacked_pallets_showcasing_efficient_space_usage_during_daytime_operations.jpg"
  },
  {
    "id": "discipline-services",
    "alt": "An engine room with valves, pipework and gauges",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoUAAsAPu1iqk2ppaQiMAgBMB2JYwCdABRvu0BYJaS/aeU2AAD+dUlI2F3Rhfa1tlho28kHaQmRsaeucunZi7TM/HXoxgAA",
    "title": "Virginia V (ship, 1922) engine room 01.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "author": "Joe Mabel",
    "source": "https://commons.wikimedia.org/wiki/File:Virginia_V_(ship,_1922)_engine_room_01.jpg"
  },
  {
    "id": "provisions",
    "alt": "Crates of fresh vegetables and greens at a wholesale market",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwBACdASoUABQAPu1ip04ppaOiMBgMATAdiWIAnQAQoL4L5J4rfjuzcqDEVsoAAP5w4x99tIV2fzIQWRbeHRE+IkUd1n4xsscCokIJXH8Gf0YkCKPYRaBX1qqBfl7EO6coH0+laAvf/c+ZrOBQYAAA",
    "title": "Outdoor market fruit and vegetable stall Market Place Romford London 01.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "author": "Acabashi",
    "source": "https://commons.wikimedia.org/wiki/File:Outdoor_market_fruit_and_vegetable_stall_Market_Place_Romford_London_01.jpg"
  },
  {
    "id": "bonded-stores",
    "alt": "Bottles of spirits on a duty-free shelf",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBQCdASoUABQAPu1qqVAppiOiqA1RMB2JaACdMoSCv8WB2EaFwG+0jfrpNWLK3V9wMAD+ofYK1EqohPVtWmTbhcZSc6SzHmo73CE1CTZou5jtOBDtdSOzGb3jfOzEukrb1c0RFoWZYZRSDsIZHed/gdGnIp79lZonAM3iwwFQAA==",
    "title": "Assorted gin bottles on a store shelf.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "author": "Jon Worth",
    "source": "https://commons.wikimedia.org/wiki/File:Assorted_gin_bottles_on_a_store_shelf.jpg"
  },
  {
    "id": "deck-stores",
    "alt": "A coil of mooring rope and wire rope on a ship's deck",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABQBACdASoUABQAPuVeo02pJSMiMAwBIByJZwDN/B4iA4PJRQx9g72de66AAP6M7elW487bbS9LtDiYxjnGSgQWPba68cN5rar5vFd02xgAAA==",
    "title": "Saga Oseberg Details Rope coil curl spiral Taukveil Timber deck Skipsdekk Wood planks Pulley block Taljeblokk Viking ship replica 2012 Tønsberg harbour havn Norway 2019-08-16 04303.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "author": "Wolfmann",
    "source": "https://commons.wikimedia.org/wiki/File:Saga_Oseberg_Details_Rope_coil_curl_spiral_Taukveil_Timber_deck_Skipsdekk_Wood_planks_Pulley_block_Taljeblokk_Viking_ship_replica_2012_T%C3%B8nsberg_harbour_havn_Norway_2019-08-16_04303.jpg"
  },
  {
    "id": "engine-stores",
    "alt": "A red-topped industrial valve with a flanged steel body",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUABQAPu1sq1GppaOiqAqpMB2JQAAFW0nOqN2gkDGN4p6vlAAA2oDNmsgmSMq8cAP9/O84Hf633Dl3oTfG9Hz0xw/HahCMaIRjrRmsKfHZ/U4eHIAAAA==",
    "title": "Small industrial control valve.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "author": "Bitjungle",
    "source": "https://commons.wikimedia.org/wiki/File:Small_industrial_control_valve.jpg"
  },
  {
    "id": "cabin-stores",
    "alt": "Folded towels and linen stacked in piles",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQBQCdASoUABQAPu1gqE8ppSOiMBgMATAdiWcAyrQPSmP8jPVItedUEse4KZEakA8ZBYAA/VM1W+vwo8U5CrJrmWTjdQ1TEaN3vDtwLgl+waG5oUuqBK8AKTYwXx9N75OXSRQA",
    "title": "HSY- Folded Towels.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "author": "HanSangYoon",
    "source": "https://commons.wikimedia.org/wiki/File:HSY-_Folded_Towels.jpg"
  },
  {
    "id": "safety-equipment",
    "alt": "An orange lifebuoy with a heaving line, mounted on a ship's rail",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBQCdASoUABQAPtlgpE2oJiOiN/qoAQAbCWQAsQ0gAq3PS8FMcKKjv1PjoDk19tSAAP7nQKkgKgNb0Pab1IL+MD4NZ4QT9O6kj9KHTViCg06akbWU7bn4iWhy4FwKMEd00FTgbdpkOCRo7ErBiL53NQtAAA==",
    "title": "Ring buoy on ship Polynesia (288580676).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "author": "Mike Schinkel from Atlanta, GA, USA",
    "source": "https://commons.wikimedia.org/wiki/File:Ring_buoy_on_ship_Polynesia_(288580676).jpg"
  },
  {
    "id": "lubricants-chemicals",
    "alt": "Workers in hard hats beside stacked drums in a store",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQBACdASoUABQAPu1qq0+ppiOiKA1RMB2JQBA8IIvCk7B/BcSxxyHuEp5Z/AAA/u5+pGlrWHlb8bT6zOyTMgivo66mk8/oH2v4uWmyRqK53NLJylxdSFFlFigAAAAA",
    "title": "ENVIRONMENTAL PROTECTION AGENCY PESTICIDES INSPECTORS DISCUSS CONTENTS OF WAREHOUSE CONTAINERS WITH AN OFFICIAL OF... - NARA - 555236.jpg",
    "license": "Public domain",
    "licenseUrl": "",
    "author": "John Messina",
    "source": "https://commons.wikimedia.org/wiki/File:ENVIRONMENTAL_PROTECTION_AGENCY_PESTICIDES_INSPECTORS_DISCUSS_CONTENTS_OF_WAREHOUSE_CONTAINERS_WITH_AN_OFFICIAL_OF..._-_NARA_-_555236.jpg"
  },
  {
    "id": "marine-paints",
    "alt": "A worker painting the blue hull of a ship from a stage",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBACdASoUABQAPu1gq1AppSOisBgIATAdiWIAnTLfAZwIK5O7Wp+n9xhAAAD+PV2/RN+eejewaf+kUGMnIofx3YoKvQNjPZLEmeJxto+h7ZUYllexzKvduzqrJEUmRwAQwnpIGWsTzAWJwmkZXQAA",
    "title": "A dock worker painting a ship's hull, Auckland - 0294.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "author": "Jorge Royan",
    "source": "https://commons.wikimedia.org/wiki/File:A_dock_worker_painting_a_ship%27s_hull,_Auckland_-_0294.jpg"
  },
  {
    "id": "electrical-stores",
    "alt": "A switchboard panel with ammeters and indicator lamps",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoUABQAPu1or1CppaQiqAqpMB2JZ2d7AAxy7y3z/SMAAPGx2NCT9BTtXN8vhKeiL5BbFQIeHXbrgkWnOiR+HDi7vrKQlw7qYATmlXhQAAA=",
    "title": "Electrical panel.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "author": "CambridgeBayWeather",
    "source": "https://commons.wikimedia.org/wiki/File:Electrical_panel.jpg"
  },
  {
    "id": "charts-publications",
    "alt": "A nautical chart with dividers, pencil and a parallel rule",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoUABQAPu1wsFKppiSiqAgBMB2JYwAAKW1wJy40SuVkANnDs3MRQxt2ELZR6kf8HB9emzISSYX6CD21dRX5ew0415yfSO1rjlETSgOSPoYAAA==",
    "title": "CYA Coastal Navigation With Dead Reckoning.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "author": "J. S. Bond",
    "source": "https://commons.wikimedia.org/wiki/File:CYA_Coastal_Navigation_With_Dead_Reckoning.JPG"
  },
  {
    "id": "medical-supplies",
    "alt": "A surgical instrument laid on a sterile blue drape",
    "ratio": "square",
    "widths": [
      900,
      450
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUABQAPu1sqlGppaOiqAqpMB2JZAC7LwAAXvjmHqgn2JgAnrDKF4Z9dHgC2z+60K8z/amwpcM2a/H/5KHtI8bsk+AaaXnJqYwqOJySnCpud2skrytJDuw3kQ2MXkQX8bAAAA==",
    "title": "Standard First Aid Kit and Essential Emergency Medical Supplies 04.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "author": "ABORISADEADETONA",
    "source": "https://commons.wikimedia.org/wiki/File:Standard_First_Aid_Kit_and_Essential_Emergency_Medical_Supplies_04.jpg"
  },
  {
    "id": "ship-repair",
    "alt": "A ship's propeller in dry dock with a worker on a staging",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAAsAPu1kqU2ppaQiMAgBMB2JYwC7ABwowlKrbai/AAD9cjJvoIX61v1WEwXm7FCa6+8wmWkQY1KnfnIKG2RW5+QAAA==",
    "title": "US Navy 030327-N-3714J-001 A contractor from National Steel and Shipping Company (NASSCO) hydro-blasts the ship's screws as part of a preservation program for the ship's hull.jpg",
    "license": "Public domain",
    "licenseUrl": "",
    "author": "U.S. Navy photo by Photographer’s Mate 3rd Class Erika Jones.",
    "source": "https://commons.wikimedia.org/wiki/File:US_Navy_030327-N-3714J-001_A_contractor_from_National_Steel_and_Shipping_Company_(NASSCO)_hydro-blasts_the_ship%27s_screws_as_part_of_a_preservation_program_for_the_ship%27s_hull.jpg"
  },
  {
    "id": "spares-procurement",
    "alt": "A brass gear wheel in a machine assembly",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwCw7CHHiTRdG8GFsq0AAP6jMauZ7S1SSpDAQjDQdGB2kTJPlQcP4NAAAA==",
    "title": "Gears on Tide Predicting Machine No. 2.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "author": "Steven Fine",
    "source": "https://commons.wikimedia.org/wiki/File:Gears_on_Tide_Predicting_Machine_No._2.jpg"
  },
  {
    "id": "motor-rewinding",
    "alt": "The copper stator winding of an electric motor",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoUAAsAPu1mqk4ppaOiMAgBMB2JZQAAMgL3v1HPf+IAAP7oj4vHHe3pFrE8QfwXc+yP22mTYYFyt8cbbqM2sp1WgleAcbAIAAA=",
    "title": "Stator Winding of a BLDC Motor.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "author": "Medvedev",
    "source": "https://commons.wikimedia.org/wiki/File:Stator_Winding_of_a_BLDC_Motor.jpg"
  },
  {
    "id": "fabrication-welding",
    "alt": "A welder striking an arc on steel plate, sparks flying",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwCdABXUAmfdGJoQAAD+8X8OP5cyJwmbPXrztdJbkzjfabp52C3Jsek+8+o5nJzUdnatiAA=",
    "title": "Metal fabrication essential to supporting MRF-D (6265765).jpg",
    "license": "Public domain",
    "licenseUrl": "",
    "author": "U.S. Marine Corps photo by Lance Cpl. Natalie Greenwood",
    "source": "https://commons.wikimedia.org/wiki/File:Metal_fabrication_essential_to_supporting_MRF-D_(6265765).jpg"
  },
  {
    "id": "mechanical-electrical",
    "alt": "A technician in safety glasses working on machinery at a bench",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQBACdASoUAAsAPu1mqk4ppaOiMAgBMB2JYwC7ACPqVfWrWzhyl4RmAAD7Fwu/8g7lSw20hDjY8gwz557WvZTHCTSXbEBEGkd4dOD/GIoALEgA",
    "title": "US Navy 030418-N-5821W-002 Aviation Structural Mechanic Airman Recruit Chris Krickle assigned to the Aircraft Intermediate Maintenance Department (AIMD) performs repair work on a Engine Air Particle Separator.jpg",
    "license": "Public domain",
    "licenseUrl": "",
    "author": "U.S. Navy photo by Journalist Seaman Stephen P. Weaver.",
    "source": "https://commons.wikimedia.org/wiki/File:US_Navy_030418-N-5821W-002_Aviation_Structural_Mechanic_Airman_Recruit_Chris_Krickle_assigned_to_the_Aircraft_Intermediate_Maintenance_Department_(AIMD)_performs_repair_work_on_a_Engine_Air_Particle_Separator.jpg"
  },
  {
    "id": "riding-squads",
    "alt": "Crew in high-visibility gear and harnesses working on deck",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JZACdMoACjqAcOfLDHHU2wwYAAPlK13XyVrUQD5bozZFkaoQ6RtqloUXNvo1ClvKGx/mheQfjvy47Y0GFsW/e9IAAAA==",
    "title": "Fugro Discovery crew members working with the search equipment (3).jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "author": "ATSB, photo by ABIS Chris Beerens, RAN",
    "source": "https://commons.wikimedia.org/wiki/File:Fugro_Discovery_crew_members_working_with_the_search_equipment_(3).jpg"
  },
  {
    "id": "turbocharger",
    "alt": "An engineer working on a turbine rotor and blades",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoUAAsAPu1iqk4ppaQiMAgBMB2JYgCdMoRwACfg84NHDUHXAAD+0PDu8k30aI7J1QhqW6nUOR8k2TmJph/vpiEQbiQYyZhTERYq/MT2ta9OMrTlI/LHmXa2IXQAAA==",
    "title": "Dampfturbine Laeufer01.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "author": "Siemens Pressebild, http://www.siemens.com",
    "source": "https://commons.wikimedia.org/wiki/File:Dampfturbine_Laeufer01.jpg"
  },
  {
    "id": "marine-pump",
    "alt": "Centrifugal and mixed-flow pump impellers",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JYgCdABZIG2BYsbdSZAD+lNj6y0h/eSg9vK50WBKoTMhp9ENJ0kndglfFJjXO7ITu83BS5zZWdqbSS13xZPQjGWgwGQAGaDAAAA==",
    "title": "Pump Impellers-1.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "author": "Meisam",
    "source": "https://commons.wikimedia.org/wiki/File:Pump_Impellers-1.jpg"
  },
  {
    "id": "hydraulic",
    "alt": "A hydraulic cylinder and machined ram",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAAsAPu1kq04ppaQiMAgBMB2JZwDE2Bn1vhJVqT0BBzgA/n6T/H+moxqWj3qDbrTPp+vKv5aA48vzOeM+VumJ2UYCF2vY0vgAAA==",
    "title": "Hydraulic press brake's cylinder.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "author": "Márton Kiss-Albert",
    "source": "https://commons.wikimedia.org/wiki/File:Hydraulic_press_brake%27s_cylinder.jpg"
  },
  {
    "id": "pcb-electronics",
    "alt": "A technician repairing electronics at a test bench",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAwCdASoUAAsAPu1iqk2ppaQiMAgBMB2JYwC7ACHgSWumq2dczqOQAP7b1M1Ju42VqcWxZmIWrcCUpMNVxI02eqAAAA==",
    "title": "USS Carl Vinson electronic repair shop operations 150219-N-HD510-015.jpg",
    "license": "Public domain",
    "licenseUrl": "",
    "author": "Feb. 19, 2015",
    "source": "https://commons.wikimedia.org/wiki/File:USS_Carl_Vinson_electronic_repair_shop_operations_150219-N-HD510-015.jpg"
  },
  {
    "id": "bridge-nav",
    "alt": "A ship's bridge console with navigation displays",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAAsAPu1kqk4ppaQiMAgBMB2JYwAAW+heQjgxTnmOAAD3yO8iAur9uQT6ikFSPs6FfgOlx23xIHmY6nEZ1quFXAAAAA==",
    "title": "Ship simulator.JPG",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "author": "Alf van Beem",
    "source": "https://commons.wikimedia.org/wiki/File:Ship_simulator.JPG"
  },
  {
    "id": "underwater-diver",
    "alt": "A commercial diver being fitted with a diving helmet",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwDCoIjDAaPlhTwQQDAA/sDk6e7YoQzY59LM4wM1yJb/10m51KelKer8LfbtX5xlR6vIZlAjh5SHm2OuYAAA",
    "title": "US Navy 050817-N-7415V-008 Hull Technician 3rd Class Zachary DiMare, left, assists Philippine Navy diver Rolando Abul during a training dive held aboard the rescue and salvage ship USS Safeguard (ARS 50).jpg",
    "license": "Public domain",
    "licenseUrl": "",
    "author": "U.S. Navy photo by Photographer's Mate 1st Class David Votroubek",
    "source": "https://commons.wikimedia.org/wiki/File:US_Navy_050817-N-7415V-008_Hull_Technician_3rd_Class_Zachary_DiMare,_left,_assists_Philippine_Navy_diver_Rolando_Abul_during_a_training_dive_held_aboard_the_rescue_and_salvage_ship_USS_Safeguard_(ARS_50).jpg"
  },
  {
    "id": "refrigeration",
    "alt": "Refrigeration compressors in a machinery plant room",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwCw7Bbb+8hOw77wDxAA/l/Zo4+a/ECerHt3Sdf/sHqxyXxbKTDWhrLowL2EgAA=",
    "title": "Reciprocating Compressor from an Industrial Refrigeration System 2.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "author": "Endora6398",
    "source": "https://commons.wikimedia.org/wiki/File:Reciprocating_Compressor_from_an_Industrial_Refrigeration_System_2.jpg"
  },
  {
    "id": "deck-winch",
    "alt": "An anchor windlass and cable on a ship's deck",
    "ratio": "wide",
    "widths": [
      1600,
      800
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAAsAPu1mq04ppaQiMAgBMB2JaQAAUh/30RmDRYtQAAD+WAU7OV+7ETQ+zR3C+oUs3PGpi0ilQ0HOAyZ9mHmWN1gAAA==",
    "title": "SS Stevens anchor windlass 01.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "author": "Wjwalrus",
    "source": "https://commons.wikimedia.org/wiki/File:SS_Stevens_anchor_windlass_01.jpg"
  }
];

export const getPhoto = (id: string) => photos.find((p) => p.id === id);
